# Generated by Django 2.2.3 on 2019-07-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
